# Generated by Django 3.2.13 on 2022-06-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
    ]
